[package]
name = "speculativefoxfacts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
megalodon = "0.8.6"
tokio = "*"
rand = "*"
reqwest = "*"
serde = {version = "*", features = ["derive"]}
